ppem2_l:
    resource: "@PPEM2LBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: PPEUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
