<?php

namespace PPE\M2LBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formationRepository extends EntityRepository
{
}
