<?php

namespace PPE\M2LBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * type_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_utilisateurRepository extends EntityRepository
{
}
