ppe_m2l_homepage:
    path:     /
    defaults: { _controller: PPEM2LBundle:Default:index }

ppe_m2l_informations:
    path:     /informations
    defaults: { _controller: PPEM2LBundle:Default:information }

ppe_m2l_reservations:
    path:     /reservations
    defaults: { _controller: PPEM2LBundle:Default:reservations }

ppe_m2l_annonces:
    path:     /annonces
    defaults: { _controller: PPEM2LBundle:Annonce:afficher }

ppe_m2l_formations:
    path:     /formations
    defaults: { _controller: PPEM2LBundle:Default:formation }

ppe_m2l_ligues:
    path:     /ligues
    defaults: { _controller: PPEM2LBundle:Default:ligue }

ppe_m2l_contact:
    path:     /contact
    defaults: { _controller: PPEM2LBundle:Default:contact }

ppe_m2l_connexion:
    path:     /login
    defaults: { _controller: PPEM2LBundle:Auth:login }

ppe_m2l_inscription:
    path:     /inscription
    defaults: { _controller: PPEM2LBundle:Auth:inscription }

ppe_m2l_account:
    path:     /account
    defaults: { _controller: PPEM2LBundle:Default:account }

ppe_m2l_back_information:
    path:    /admin/listeinfo
    defaults: { _controller: PPEM2LBundle:Admin:getinformations}

ppe_m2l_back_informations:
    path:    /admin/informations
    defaults: { _controller: PPEM2LBundle:Admin:addinformation}

ppe_m2l_back_info:
    path:    /admin/editinfo/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editinformation}
    requirements:
        id: \d+

ppe_m2l_back_annonce:
    path:    /admin/listeannonce
    defaults: { _controller: PPEM2LBundle:Admin:getannonces}

ppe_m2l_back_annonces:
    path:    /admin/annonces
    defaults: { _controller: PPEM2LBundle:Admin:addannonce}

ppe_m2l_back_annonceedit:
    path:    /admin/editannonce/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editannonce}
    requirements:
        id: \d+
