# Accueil
ppe_m2l_homepage:
    path:     /
    defaults: { _controller: PPEM2LBundle:Default:index }

ppe_m2l_back_actualite:
    path:    /admin/listeactualite
    defaults: { _controller: PPEM2LBundle:Admin:getactualites}

ppe_m2l_back_actualites:
    path:    /admin/actualites
    defaults: { _controller: PPEM2LBundle:Admin:addactualite}

ppe_m2l_back_actu:
    path:    /admin/editactu/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editactualite}
    requirements:
        id: \d+

ppe_m2l_back_delete_actualites:
    path:    /admin/deleteactualite/{id}
    defaults: { _controller: PPEM2LBundle:Admin:deleteactualite}
    requirements:
        id: \d+

# Fin Accueil

# Informations
ppe_m2l_informations:
    path:     /informations
    defaults: { _controller: PPEM2LBundle:Default:information }

ppe_m2l_back_information:
    path:    /admin/listeinfo
    defaults: { _controller: PPEM2LBundle:Admin:getinformations}

ppe_m2l_back_informations:
    path:    /admin/informations
    defaults: { _controller: PPEM2LBundle:Admin:addinformation}

ppe_m2l_back_info:
    path:    /admin/editinfo/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editinformation}
    requirements:
        id: \d+

ppe_m2l_back_delete_informations:
    path:    /admin/deleteinformation/{id}
    defaults: { _controller: PPEM2LBundle:Admin:deleteinformation}
    requirements:
        id: \d+

# Fin Informations

# Reservations
ppe_m2l_reservations:
    path:     /reservations
    defaults: { _controller: PPEM2LBundle:Default:reservations }
# Fin Reservations

# Annonces 
ppe_m2l_annonces:
    path:     /annonces
    defaults: { _controller: PPEM2LBundle:Annonce:afficher }

ppe_m2l_back_annonce:
    path:    /admin/listeannonce
    defaults: { _controller: PPEM2LBundle:Admin:getannonces}

ppe_m2l_back_annonces:
    path:    /admin/annonces
    defaults: { _controller: PPEM2LBundle:Admin:addannonce}

ppe_m2l_back_annonceedit:
    path:    /admin/editannonce/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editannonce}
    requirements:
        id: \d+

ppe_m2l_back_delete_annonces:
    path:    /admin/deleteannonce/{id}
    defaults: { _controller: PPEM2LBundle:Admin:deleteannonce}
    requirements:
        id: \d+
# Fin Annonces

# Formations
ppe_m2l_formations:
    path:     /formations
    defaults: { _controller: PPEM2LBundle:Default:formation }

ppe_m2l_back_formation:
    path:    /admin/listeformation
    defaults: { _controller: PPEM2LBundle:Admin:getformations}

ppe_m2l_back_formations:
    path:    /admin/formations
    defaults: { _controller: PPEM2LBundle:Admin:addformation}

ppe_m2l_back_formationedit:
    path:    /admin/editformation/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editformation}
    requirements:
        id: \d+

ppe_m2l_back_delete_formations:
    path:    /admin/deleteformation/{id}
    defaults: { _controller: PPEM2LBundle:Admin:deleteformation}
    requirements:
        id: \d+

# Fin Formations

# Ligues
ppe_m2l_ligues:
    path:     /ligues
    defaults: { _controller: PPEM2LBundle:Default:ligue }

ppe_m2l_back_list_ligues:
    path:    /admin/listligues
    defaults: { _controller: PPEM2LBundle:Admin:getligues}

ppe_m2l_back_edit_ligues:
    path:    /admin/editligues/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editligue}
    requirements:
        id: \d+

ppe_m2l_back_delete_ligues:
    path:    /admin/deleteligue/{id}
    defaults: { _controller: PPEM2LBundle:Admin:deleteligue}
    requirements:
        id: \d+

ppe_m2l_ligue_maligue:
    path:    /maligue
    defaults: { _controller: PPEM2LBundle:Admin:maLigue}

ppe_m2l_edit_maligue:
    path:    /maligue/edit/{id}
    defaults: { _controller: PPEM2LBundle:Admin:editMaLigue}
    requirements:
        id: \d+
# Fin Ligues

# Contact
ppe_m2l_contact:
    path:     /contact
    defaults: { _controller: PPEM2LBundle:Contact:contact }
# Fin Contact

# Authentification

ppe_m2l_inscription:
    path:     /inscription
    defaults: { _controller: PPEM2LBundle:Auth:inscription }

ppe_m2l_account:
    path:     /account
    defaults: { _controller: PPEM2LBundle:Default:account }
# Fin Authentification

ppe_m2l_admin_panel:
    path:     /admin/
    defaults: { _controller: PPEM2LBundle:Admin:adminPanel }

